[package]
name = "ore-rs"
version = "0.1.0"
authors = ["Dan Draper <dan@cipherstash.com>"]
edition = "2018"
homepage = "http://ore.rs"
description = "Order-revealing encryption library used by the CipherStash searchable encryption platform"
license-file = "COPYING"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dev-dependencies]
criterion = "0.3.5"
quickcheck = "1.0.3"

[dependencies]
aes = { version = "0.7.5", features = ["armv8"]}
block-modes = "0.8.1"
hex-literal = "0.3.2"
rand = "0.3.1"
rand_chacha = "0.3.1"
num = "0.4.0"
serde = { version = "1.0.132", features = ["derive"]}
bincode = "1.3.3"

[[bench]]
name = "oreaes128"
harness = false
