[package]
name = "ore"
version = "0.1.0"
authors = ["Dan Draper <dan@cipherstash.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dev-dependencies]
criterion = "0.3.5"
fake = "2.4.0"
quickcheck = "1.0.3"

[dependencies]
aes = { version = "0.7.5", features = ["armv8"]}
block-modes = "0.8.1"
byteorder = "1.4.3"
hex-literal = "0.3.2"
rand = "0.3.1"
rand_chacha = "0.3.1"
num = "0.4.0"


[[bench]]
name = "oreaes128"
harness = false
