[package]
name = "small_prp"
version = "0.1.0"
authors = ["Dan Draper <dan@coderdan.co>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dev-dependencies]
criterion = "0.3"
fake = "2.4.0"
quickcheck = "1.0.3"

[dependencies]
aes = "0.7.4"
block-modes = "0.8.1"
byteorder = "1.4.3"
hex-literal = "0.3.2"
rand = "0.3.1"
rand_chacha = "0.3.1"

[[bench]]
name = "large_domain"
harness = false
